# Site settings
title: Evridiki Kourachani
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Evridiki Kourachani
user_description: I'm an Aspiring Data Scientist from Athens,Greece always searching for the next challenge. 
user_title: Data Scientist
email: euridikh.96@gmail.com
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: Evridiki Kourachani
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

